#!/usr/bin/python

from imgFuncs import *
from ann import *
import os
import sys
import argparse

def main():
    # Parse command line args
    parser = argparse.ArgumentParser(prog='ocr')
    parser.add_argument('-t', '--train_dir', type=str, default=None,
        help='train OCR on the images in a properly-structured directory of character images')
    parser.add_argument('-d', '--dimension', type=int, default=10,
        help='length of side of converted bmp image (default is 10)')
    parser.add_argument('-k', '--keep', action='store_true', default=True,
        help='flag to set whether or not to keep converted training/testing images (default is True)')
    parser.add_argument('-n', '--new', action='store_true',
        help='flag to set whether or not to remake all the formatted images for a training directory if it already exists (default is False)')
    parser.add_argument('-s', '--structure', type=str, default=None,
        help='file containing structure of ANN')
    parser.add_argument('-w', '--weights', type=str, default=None,
        help='file containing ANN\'s starting weights (default is start with random weights)')
    parser.add_argument('-a', '--alpha', type=float, default=0.001,
        help='the alpha value for error propagation')
    parser.add_argument('-i', '--iters', type=int, default=200,
        help='number of training iterations to run on the training images')
    args = parser.parse_args()

    # Format the images for the ANN
    if args.train_dir and os.path.isdir(args.train_dir) and args.structure:
        formatted_dir = args.train_dir.split('/')[0] + 'Formatted'

        # Only remake all the images if the formatted images directory doesn't
        # exist OR the user wants to remake all the formatted images regardless
        if args.new or not os.path.isdir(formatted_dir):
            if os.path.isdir(formatted_dir):
                shutil.rmtree(formatted_dir)
            create_formatted(args.train_dir, formatted_dir, args.dimension)

        # DO ANN THINGS
        my_ann = ANN(formatted_dir, args.structure, args.alpha, args.iters)
        my_ann.get_num_chars()
        my_ann.build()

        if raw_input('Save ANN? [y/n]: ') in ['y', 'Y']:
            my_ann.save()

        # Remove the old traning images directory before creating new ones
        if not args.keep and os.path.isdir(formatted_dir):
            shutil.rmtree(formatted_dir)
    else:
        print("ERROR: must provide name of properly-structured images directory and structure file")


if __name__ == '__main__':
    main()
