#!/usr/bin/python

from imgFuncs import *
import os
import sys
import argparse

def main():
    # Parse command line args
    parser = argparse.ArgumentParser(prog='ocr')
    parser.add_argument('--dir', type=str, default=None,
        help='properly format images in the given directory for the ANN to train')
    parser.add_argument('--side', type=int, default=10,
        help='length of side of converted bmp image (default is 10)')
    parser.add_argument('--delete', type=bool, default=False,
        help='delete the "<images directory>Bmps" directory instead of making another')
    args = parser.parse_args()

    # Format the images for the ANN
    if args.dir and os.path.isdir(args.dir):
        trainDir = args.dir + 'Trainable'
        createBmps(args.dir, trainDir, args.side)

        # Remove the old traning images directory before creating new ones
        if args.delete and os.path.isdir(trainDir):
            shutil.rmtree(trainDir)
        else:
    else:
        print("ERROR: must provide name of properly-structured images directory")
        exit(1)


if __name__ == '__main__':
    main()
